# (re)build docker build container template
.docker_template:
  stage: dockers
  image: docker:latest
  services:
    - docker:dind
  variables: &docker_variables
    DOCKER_DRIVER: overlay
    DOCKER_HOST: "tcp://localhost:2375"
  script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE/$IMAGE || true
    - docker build --pull --cache-from $CI_REGISTRY_IMAGE/$IMAGE -t $CI_REGISTRY_IMAGE/$IMAGE $IMAGE
    - docker push $CI_REGISTRY_IMAGE/$IMAGE
  dependencies: []

.chroots_template:
  stage: chroots
  image: $CI_REGISTRY_IMAGE/ubuntu-pbuilder
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - coda-deb-build/chroots/
  script: ./build-deb-chroots.sh $CI_JOB_NAME
  dependencies: []
  artifacts:
    paths:
      - coda-deb-build/chroots/
    expire_in: 1 day
  only:
    changes:
      - build-deb-chroots.sh
      - coda-deb-build/*

.build_deb:
  stage: build
  image: registry.cmusatyalab.org/coda/coda-packaging/coda-deb-build:latest
  script: ./build-debs.sh $CI_JOB_NAME
  artifacts:
    paths:
      - dist/
    expire_in: 1 week
  dependencies:
    - fetch-coda-source

.build_rpm:
  stage: build
  image: registry.cmusatyalab.org/coda/coda-packaging/coda-rpm-build:latest
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - cache/
  script: ./build-rpms.sh $CI_JOB_NAME
  artifacts:
    paths:
      - dist/*.rpm
    expire_in: 1 week
  dependencies:
    - fetch-coda-source

